### PR TITLE
Set up a "Hello world" project with two apps

### PR DESCRIPTION
**Pull request by Aduda-Boaz**
## Project requirements
- Created a new Rails API app called 'rails-back-end-API.
- An initialized project with Git.
- The project has a Postgres database set up.
- Created a table for storing messages and created 5 different greetings.
- Created an API endpoint that selects a random greeting from the table.
    - Create a new React app called 'hello-react-front-end'
          - Initialized the project with Git.
          - Created the App component with react-router.
          - Create the Greeting component that will display a greeting.
          - Create a store, an action and a reducer that will connect to the API endpoint to get the random greeting.
          - Display the random greeting in the Greeting component.

### CODE REVIEW

**Review by Deepakdanger — COMMENTED** [review]
Hi @Aduda-Boaz, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that In the repo for the frontend part there is no PR with changes. Please make sure that You have also opened a PR in the frontend app.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

**Review by rotimiazeez — CHANGES_REQUESTED** [review]
# Hi @Aduda-Boaz  👍🏽, 
## Good job so far! 👍🏽 
### Summary ♨️ 
- No Linter error ✔️ 
- Good and descriptive PR 💯
- Good commit messages 👍🏽
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights


## Required Changes ♻️
_Check the comments under the review._
- [x] Kindly make sure you implement `store`  and `reducer` in your frontend PR

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Aduda-Boaz** [comment]
implemented stores and reduces in front-end

**Review by sja-thedude — APPROVED** [review]
## Project Approved 👍 

Hi @Aduda-Boaz, This is @sja-thedude your code reviewer.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Highlights:
- All linters passing
- All requirements completed
- Professional readme

giphy

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
